CREATE PROCEDURE ALTERA_CONTAS
	@ID INT,
	@NOME VARCHAR(50),
	@DESCRICAO VARCHAR(255),
	@DTVENCIMENTO SMALLDATETIME,
	@TIPO TINYINT,
	@STATUS TINYINT,
	@DTPAGAMENTO SMALLDATETIME,
	@VALOR MONEY
AS
BEGIN
	UPDATE CONTAS
	SET
		NOMECONTA = @NOME,
		DESCRICAOCONTA = @DESCRICAO,
		DTVALCONTA = @DTVENCIMENTO,
		TIPOCONTA = @TIPO,
		STATUSCONTA = @STATUS,
		DTPAGCONTA = @DTPAGAMENTO,
		VALORCONTA = @VALOR
	WHERE IDCONTA = @ID
END