CREATE PROCEDURE SELECIONA_CONTAS
	@ID int
AS
BEGIN
	IF(ISNULL(@ID,0) = 0)
		SELECT NOMECONTA, DESCRICAOCONTA, DTVALCONTA, 
		TIPOCONTA,
			CASE
				WHEN TIPOCONTA = 1 THEN 'Boleto'
				WHEN TIPOCONTA = 2 THEN 'Fatura'
				WHEN TIPOCONTA = 3 THEN 'Despesa'
			END AS TIPO_TEXTO
		, STATUSCONTA, 
			CASE
				WHEN STATUSCONTA = 1 THEN 'Pendente'
				WHEN STATUSCONTA = 2 THEN 'Liquidado'
				WHEN STATUSCONTA = 3 THEN 'Vencido'
			END AS STATUS_TEXTO
		,DTPAGCONTA, VALORCONTA, IDCONTA FROM CONTAS WITH(NOLOCK)
		
	ELSE
		SELECT NOMECONTA, DESCRICAOCONTA, DTVALCONTA, 
		TIPOCONTA,
			CASE
				WHEN TIPOCONTA = 1 THEN 'Boleto'
				WHEN TIPOCONTA = 2 THEN 'Fatura'
				WHEN TIPOCONTA = 3 THEN 'Despesa'
			END AS TIPO_TEXTO
		, STATUSCONTA, 
			CASE
				WHEN STATUSCONTA = 1 THEN 'Pendente'
				WHEN STATUSCONTA = 2 THEN 'Liquidado'
				WHEN STATUSCONTA = 3 THEN 'Vencido'
			END AS STATUS_TEXTO
		,DTPAGCONTA, VALORCONTA, IDCONTA FROM CONTAS WITH(NOLOCK) WHERE IDCONTA = @ID
END