USE ControleDeContas
go

IF EXISTS (SELECT * FROM sysobjects WHERE type = 'P' AND name = 'ADICIONA_CONTAS')
BEGIN
	PRINT 'Dropping Procedure ADICIONA_CONTAS'
	DROP PROCEDURE ADICIONA_CONTAS
END
GO
PRINT 'Creating Procedure ADICIONA_CONTAS'
GO

CREATE PROCEDURE ADICIONA_CONTAS
	@NOME VARCHAR(50),
	@DESCRICAO VARCHAR(255),
	@DTVENCIMENTO SMALLDATETIME,
	@TIPO TINYINT,
	@STATUS TINYINT,
	@DTPAGAMENTO SMALLDATETIME,
	@VALOR MONEY
AS
BEGIN
	INSERT INTO CONTAS (NOMECONTA, DESCRICAOCONTA, DTVALCONTA, TIPOCONTA, STATUSCONTA, DTPAGCONTA, VALORCONTA)
	VALUES (@NOME, @DESCRICAO, @DTVENCIMENTO, @TIPO, @STATUS, @DTPAGAMENTO, @VALOR)

	SELECT SCOPE_IDENTITY()
END
go

IF EXISTS (SELECT * FROM sysobjects WHERE type = 'P' AND name = 'ALTERA_CONTAS')
BEGIN
	PRINT 'Dropping Procedure ALTERA_CONTAS'
	DROP PROCEDURE ALTERA_CONTAS
END
GO
PRINT 'Creating Procedure ALTERA_CONTAS'
GO

CREATE PROCEDURE ALTERA_CONTAS
	@ID INT,
	@NOME VARCHAR(50),
	@DESCRICAO VARCHAR(255),
	@DTVENCIMENTO SMALLDATETIME,
	@TIPO TINYINT,
	@STATUS TINYINT,
	@DTPAGAMENTO SMALLDATETIME,
	@VALOR MONEY
AS
BEGIN
	UPDATE CONTAS
	SET
		NOMECONTA = @NOME,
		DESCRICAOCONTA = @DESCRICAO,
		DTVALCONTA = @DTVENCIMENTO,
		TIPOCONTA = @TIPO,
		STATUSCONTA = @STATUS,
		DTPAGCONTA = @DTPAGAMENTO,
		VALORCONTA = @VALOR
	WHERE IDCONTA = @ID
END
go

IF EXISTS (SELECT * FROM sysobjects WHERE type = 'P' AND name = 'SELECIONA_CONTAS')
BEGIN
	PRINT 'Dropping Procedure SELECIONA_CONTAS'
	DROP PROCEDURE SELECIONA_CONTAS
END
GO
PRINT 'Creating Procedure SELECIONA_CONTAS'
GO
CREATE PROCEDURE SELECIONA_CONTAS
	@ID int
AS
BEGIN
	IF(ISNULL(@ID,0) = 0)
		SELECT NOMECONTA, DESCRICAOCONTA, DTVALCONTA, 
		TIPOCONTA,
			CASE
				WHEN TIPOCONTA = 1 THEN 'Boleto'
				WHEN TIPOCONTA = 2 THEN 'Fatura'
				WHEN TIPOCONTA = 3 THEN 'Despesa'
			END AS TIPO_TEXTO
		, STATUSCONTA, 
			CASE
				WHEN STATUSCONTA = 1 THEN 'Pendente'
				WHEN STATUSCONTA = 2 THEN 'Liquidado'
				WHEN STATUSCONTA = 3 THEN 'Vencido'
			END AS STATUS_TEXTO
		,DTPAGCONTA, VALORCONTA, IDCONTA FROM CONTAS WITH(NOLOCK)
		
	ELSE
		SELECT NOMECONTA, DESCRICAOCONTA, DTVALCONTA, 
		TIPOCONTA,
			CASE
				WHEN TIPOCONTA = 1 THEN 'Boleto'
				WHEN TIPOCONTA = 2 THEN 'Fatura'
				WHEN TIPOCONTA = 3 THEN 'Despesa'
			END AS TIPO_TEXTO
		, STATUSCONTA, 
			CASE
				WHEN STATUSCONTA = 1 THEN 'Pendente'
				WHEN STATUSCONTA = 2 THEN 'Liquidado'
				WHEN STATUSCONTA = 3 THEN 'Vencido'
			END AS STATUS_TEXTO
		,DTPAGCONTA, VALORCONTA, IDCONTA FROM CONTAS WITH(NOLOCK) WHERE IDCONTA = @ID
END
go

IF EXISTS (SELECT * FROM sysobjects WHERE type = 'P' AND name = 'DELETA_CONTAS')
BEGIN
	PRINT 'Dropping Procedure DELETA_CONTAS'
	DROP PROCEDURE DELETA_CONTAS
END
GO
PRINT 'Creating Procedure DELETA_CONTAS'
GO

CREATE PROCEDURE DELETA_CONTAS
		@ID INT
AS
BEGIN
	DELETE CONTAS WHERE IDCONTA = @ID
END
go